### ISSUE TITLE
Rscript not found

### ISSUE THREAD

**Issue by sckott** [metacran/r-builder#28]
https://travis-ci.org/ropensci/solrium/jobs/77379415#L3031

hmm, i wonder why that works when using `language: r`, or when using `r-travis`, but not it with r-builder?

any tips on what's wrong?

**Comment by gaborcsardi** [comment]
It's because the other solutions install R/Rscript from the OS package and it is in /usr/bin.

r-builder installs different versions of R, each in its own directory, and these are not in the PATH by default. I could make a link in /usr/local/bin or /usr/bin, but I was going towards the new Travis infrastructure, and the link needs sudo.

**Comment by sckott** [comment]
Hmm, but in #20 seems like you have given up on the new style

**Comment by gaborcsardi** [comment]
Not yet, sorry if it was misleading. The new style needs manual caching, Travis caching does not work very well. So until there is caching, it is not worth it.

**Comment by sckott** [comment]
any sol'n for now? could I add it to the PATH manually?

**Comment by gaborcsardi** [comment]
You can use `run_script`: https://github.com/metacran/r-builder/blob/master/pkg-build.sh#L445 

E.g.

```
...
  - ./pkg-build.sh run_script
...
```

**Comment by sckott** [comment]
nice, thanks
