### ISSUE TITLE
Checking with ASAN / UBSAN on Travis CI?

### ISSUE THREAD

**Issue by HenrikBengtsson** [metacran/r-builder#33]
Possibly off-topic for r-builder/pkg-build.sh, but I find this place to be my best shot to reach Travis CI savvy folks:

Does anyone know how to run `R CMD check` on Travis CI with:
* Addess Sanitizer (ASAN)
* "Undefined Behavior Sanitizer" (UBSAN)
enabled? 

As far as I understand it UBSAN requires GCC (>= 4.9.0), but Travis CI only provides GCC 4.6.3 for `language: c`.
```r
$ gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
```
so I guess this is the first of possibly several hurdles to overcome.

Comments?

PS. I'm already [running jobs](https://travis-ci.org/HenrikBengtsson/illuminaio) that use `R CMD check --use-valgrind`, but I'd love to check with ASAN/UBSAN powers as well.

PS. Explicit CC to @eddelbuettel

**Comment by gaborcsardi** [comment]
I don't know of any asan or ubsan solution for travis, but I suspect that it must exist. As you noted, you need to install your own compiler for this, and we would probably also need new R binary builds.

If technically possible, I don't mind supporting this at all. 

The only "hurdle" is, that I want to see what happens to my r-hub proposal (https://github.com/r-hub/proposal), because the fate of that largely determines what happens to r-builder. If r-hub happens, then r-builder will be probably superseded by r-hub. If r-hub does not happen, then r-builder will live on. :)

So I'll come back to many of the improvements in a couple of weeks, hopefully.

**Comment by eddelbuettel** [comment]
Not your own, just a recent one for either clang/clang++ or gcc/g++.  That's how I built the two corresponding Dockerfiles.   Then, given the compiler, you need to instrument R accordingly.

This would indeed be very nice to have on r-hub.

**Comment by gaborcsardi** [comment]
Yes, technically not my own, but I need an R build that was built with the same compiler, and on Travis this means a back-ported compiler, which probably means that I'll need to build R for myself, because of the strange platform (old distrib with some backported packages).

On r-hub this would be much simpler of course, because we can just use your Dockerfiles directly, and that's it. :)

**Comment by gaborcsardi** [comment]
Btw. Travis also supports now your own containers, but I haven't looked at that yet, so I am not sure what exactly it means in practice. This is also a completely new direction, so I would not go there, unless necessary. :)

**Comment by eddelbuettel** [comment]
Same here -- know they do, haven't had time to play yet.

**Comment by HenrikBengtsson** [comment]
Thanks for the feedback.  What is still not clear to me is if/why R itself has to be built with the same compiler as my package tested in order for ASAN/UBSAN to work.  Is that for sure the case?

**Comment by gaborcsardi** [comment]
You don't necessarily need the same compiler AFAIK, but there is some chance that compiling packages with 4.9.x does not work if R was compiled with 4.6.x. 

IMO it is the best if everything is compiled with the same compiler, then you don't need to override any of R's flags, and you can be sure that the binaries are compatible.

**Comment by gaborcsardi** [comment]
No need, no interest. Use the proper Travis support for R.
